version: '3.8'

services:
  database:
    image: postgres:alpine3.18
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: avito
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ../migrations/data.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data/pgdata
  server:
    build:
      context: ..
      dockerfile: ./Dockerfile
    depends_on:
      database:
        condition: service_started
    ports:
      - 80:80
    volumes:
      - csv:/some/path/to/mounted/volume

volumes:
  pgdata:
  csv:
